/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entity.Libro;
import entity.Prestito;
import entity.Utente;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Classe che modella l'interfaccia relativa alla restituzione del libro
 * @author donatotanieli
 */
public class ResoLibroGUI extends javax.swing.JFrame {
    
    private JFrame f;
    private Prestito p;

    /**
     * Creates new form ResoLibroGUI
     * @param f
     * @param p
     */
    public ResoLibroGUI(JFrame f, Prestito p) {
        initComponents();
        this.f = f;
        this.p = p;
        setLabels(p);
    }
    
    /**
     * Metodo che setta le Label con i dati del prestito
     * @param p 
     */
    private void setLabels(Prestito p){
        //Ottengo il riferimento dell'utente
        Utente u = p.getUtente();
        //Ottengo il riferimento del libro
        Libro l = p.getLibro();
        
        //Setto le label dei dati dell'utente
        labelNome.setText(u.getNome() + " " + u.getCognome());
        labelData.setText( u.getData().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")));
        labelTelefono.setText(u.getTelefono());
        
        //Setto le label dei dati del libro
        labelTitolo.setText(l.getTitolo());
        labelAutore.setText(l.getAutore());
        labelAnno.setText(String.valueOf(l.getAnno()));
        labelPrestito.setText(p.getInizioPrestito().format(DateTimeFormatter.ofPattern("HH:mm dd-MMM-yyyy")));
        labelIbsn.setText(l.getIbsn());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        labelTitolo = new javax.swing.JLabel();
        labelAutore = new javax.swing.JLabel();
        labelAnno = new javax.swing.JLabel();
        labelIbsn = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelPrestito = new javax.swing.JLabel();
        btnAccetta = new javax.swing.JButton();
        btnAnnulla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("RESO LIBRO");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Riepilogo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Dati Utente:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-Reso.png"))); // NOI18N

        labelNome.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelNome.setText("labelNome");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendar-Reso.png"))); // NOI18N

        labelData.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelData.setText("labelData");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/phone-Reso.png"))); // NOI18N

        labelTelefono.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelTelefono.setText("labelTelefono");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(labelTelefono))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(labelData))
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(labelNome)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(labelNome)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelData)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTelefono, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(23, 23, 23))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Dati Libro:");

        labelTitolo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelTitolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addBookMenu.png"))); // NOI18N
        labelTitolo.setText("labelTitolo");

        labelAutore.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelAutore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/authors-icon.png"))); // NOI18N
        labelAutore.setText("labelAtuore");

        labelAnno.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelAnno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendar-Reso.png"))); // NOI18N
        labelAnno.setText("labelAnno");

        labelIbsn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelIbsn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Barcode-icon.png"))); // NOI18N
        labelIbsn.setText("labelIbsn");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Prestato il:");

        labelPrestito.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelPrestito.setText("labelPrestito");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitolo)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAutore)
                                    .addComponent(labelIbsn))
                                .addGap(218, 218, 218)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelPrestito))
                                    .addComponent(labelAnno))))))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(labelTitolo)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAutore)
                    .addComponent(labelAnno))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIbsn)
                    .addComponent(jLabel7)
                    .addComponent(labelPrestito))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAccetta.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnAccetta.setForeground(new java.awt.Color(0, 51, 255));
        btnAccetta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok-icon.png"))); // NOI18N
        btnAccetta.setText("Accetta Reso");
        btnAccetta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccettaActionPerformed(evt);
            }
        });

        btnAnnulla.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnAnnulla.setForeground(new java.awt.Color(0, 51, 255));
        btnAnnulla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnAnnulla.setText("Annulla");
        btnAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnullaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(btnAccetta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAnnulla, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnnulla)
                    .addComponent(btnAccetta))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * ActionPerformed del Button Accetta Reso
     * @param evt 
     */
    private void btnAccettaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccettaActionPerformed
        if(((BibliotecaGUI)f).getBiblioteca().rendiLibro(p)){
            p.setFinePrestito(LocalDateTime.now());
            JOptionPane.showMessageDialog(null, "Reso effettuato!", "RESO", JOptionPane.INFORMATION_MESSAGE);
            ((BibliotecaGUI)f).aggiornaTabella(2); //Aggiorno la tabella dei prestiti
            ((BibliotecaGUI)f).aggiornaTabella(1); //Aggiorno la tabella dei libri
        }else{
            JOptionPane.showMessageDialog(null, "Non è stato possibile effettuare il reso!", "RESO", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAccettaActionPerformed

    /**
     * ActionPerformed del Button Annulla
     * @param evt 
     */
    private void btnAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnullaActionPerformed
        dispose();
    }//GEN-LAST:event_btnAnnullaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccetta;
    private javax.swing.JButton btnAnnulla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelAnno;
    private javax.swing.JLabel labelAutore;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelIbsn;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPrestito;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTitolo;
    // End of variables declaration//GEN-END:variables
}
